
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.brevy.spring.cxf.ws.services.fc.converter.impl;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import com.brevy.spring.cxf.ws.services.fc.converter.ConvertCType;
import com.brevy.spring.cxf.ws.services.fc.converter.ConverterPortType;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-03T11:26:56.605+08:00
 * Generated source version: 2.7.5
 * 
 */
@Component("converterService")
@javax.jws.WebService(
                      serviceName = "ConverterService",
                      portName = "ConverterPort",
                      targetNamespace = "http://cxf.spring.brevy.com/services/FC/Converter",
                      endpointInterface = "com.brevy.spring.cxf.ws.services.fc.converter.ConverterPortType")
                      
public class ConverterPortTypeImpl implements ConverterPortType {

	private transient Logger log = LoggerFactory.getLogger(this.getClass());
	
    /* (non-Javadoc)
     * @see com.brevy.spring.cxf.ws.services.fc.converter.ConverterPortType#convert(com.brevy.spring.cxf.ws.services.fc.converter.ConvertCType  converterRequestPart )*
     */
    public String convert(ConvertCType converterRequestPart) { 
        log.info("Executing operation convert");
        try {
        	return Integer.toString(converterRequestPart.getParam(), converterRequestPart.getRadix());
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
